defmodule Inkwell.Repo.Migrations.InitializeRecentFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recent_files, primary_key: false) do
      add :open_count, :bigint, null: false
      add :last_opened_at, :utc_datetime_usec, null: false
      add :path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:recent_files, [:path], name: "recent_files_unique_path_index")
  end

  def down do
    drop_if_exists unique_index(:recent_files, [:path], name: "recent_files_unique_path_index")

    drop table(:recent_files)
  end
end